package moa.mymoney.hmapping;
// Generated 22 oct. 2012 15:42:07 by Hibernate Tools 3.2.1.GA



/**
 * Banque generated by hbm2java
 */
public class Banque  implements java.io.Serializable {


     private int id;
     private String name;
     private String adresse;
     private String contact;

    public Banque() {
    }

	
    public Banque(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Banque(int id, String name, String adresse, String contact) {
       this.id = id;
       this.name = name;
       this.adresse = adresse;
       this.contact = contact;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }




}


