package moa.mymoney.hmapping;
// Generated 22 oct. 2012 15:42:07 by Hibernate Tools 3.2.1.GA



/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private int id;
     private String name;
     private int banque;
     private int solde;
     private Integer money;
     private Integer type;

    public Compte() {
    }

	
    public Compte(int id, String name, int banque, int solde) {
        this.id = id;
        this.name = name;
        this.banque = banque;
        this.solde = solde;
    }
    public Compte(int id, String name, int banque, int solde, Integer money, Integer type) {
       this.id = id;
       this.name = name;
       this.banque = banque;
       this.solde = solde;
       this.money = money;
       this.type = type;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getBanque() {
        return this.banque;
    }
    
    public void setBanque(int banque) {
        this.banque = banque;
    }
    public int getSolde() {
        return this.solde;
    }
    
    public void setSolde(int solde) {
        this.solde = solde;
    }
    public Integer getMoney() {
        return this.money;
    }
    
    public void setMoney(Integer money) {
        this.money = money;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }




}


