package moa.mymoney.hmapping;
// Generated 22 oct. 2012 15:42:07 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation  implements java.io.Serializable {


     private int id;
     private int type;
     private int tiers;
     private Date date;
     private int category;
     private Integer subcategory;
     private int debit;
     private int credit;

    public Operation() {
    }

	
    public Operation(int id, int type, int tiers, Date date, int category, int debit, int credit) {
        this.id = id;
        this.type = type;
        this.tiers = tiers;
        this.date = date;
        this.category = category;
        this.debit = debit;
        this.credit = credit;
    }
    public Operation(int id, int type, int tiers, Date date, int category, Integer subcategory, int debit, int credit) {
       this.id = id;
       this.type = type;
       this.tiers = tiers;
       this.date = date;
       this.category = category;
       this.subcategory = subcategory;
       this.debit = debit;
       this.credit = credit;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public int getTiers() {
        return this.tiers;
    }
    
    public void setTiers(int tiers) {
        this.tiers = tiers;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getCategory() {
        return this.category;
    }
    
    public void setCategory(int category) {
        this.category = category;
    }
    public Integer getSubcategory() {
        return this.subcategory;
    }
    
    public void setSubcategory(Integer subcategory) {
        this.subcategory = subcategory;
    }
    public int getDebit() {
        return this.debit;
    }
    
    public void setDebit(int debit) {
        this.debit = debit;
    }
    public int getCredit() {
        return this.credit;
    }
    
    public void setCredit(int credit) {
        this.credit = credit;
    }




}


