package moa.mymoney.hmapping;
// Generated 22 oct. 2012 15:42:07 by Hibernate Tools 3.2.1.GA



/**
 * Tiers generated by hbm2java
 */
public class Tiers  implements java.io.Serializable {


     private int id;
     private String name;

    public Tiers() {
    }

    public Tiers(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


